# reporter.py
"""
Handles the generation and printing of the final log monitoring report.
"""

def print_final_report(report_entries, lines_processed_count):
    """
    Prints the consolidated report.

    Args:
        report_entries (list): A list of strings, where each string is a report message.
        lines_processed_count (int): Total number of non-empty lines processed from the log.
    """
    print("\n--- Log Monitoring Report ---")

    if not report_entries:
        if lines_processed_count > 0:
            # This case means lines were processed, but no anomalies, warnings, or errors were generated by the processor.
            print("No significant events, warnings, or errors found requiring reporting.")
            print(f"All {lines_processed_count} processed log entries for jobs were within defined thresholds.")
        # If lines_processed_count is 0 and report_entries is empty,
        # the "empty file" message should have been added by main.py before calling this.
    else:
        for message in report_entries:
            print(message)

    print("--- End of Report ---")